language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

install:
  - sudo apt-get install jedit

before_script:
  - cp build.properties.in build.properties

# Run the Build script
script:
  - ant

# Notify the mailing list
notifications:
 email:
   on_success: change
   on_failure: always
