language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

before_install:
  - git submodule update --init --recursive

install:
  - sudo apt-get install jedit subversion

before_script:
  - svn co https://svn.code.sf.net/p/jedit/svn/build-support/trunk build-support
  - cp build.properties.in build.properties

# Run the Build script
script:
  - ant

# Notify the mailing list
notifications:
 email:
   on_success: change
   on_failure: always
